Add python interface by pybind11, add Int8 mode, add distill-resnet18 backbone support
JDAI-CV/fast-reid pull request #433
Opened 2021-03-16 08:41 UTC by tycallen

2021-03-16 08:51 UTC, L1aoXingyu commented
@TCHeish Please help review this PR.

2021-03-16 09:18 UTC, TCHeish commented
> @TCHeish Please help review this PR.

Sure!

2021-03-17 14:25 UTC, TCHeish requested changes
1. the distill-r18 backbone part is ok.
2. the pybind11 part. 
It might require some changes, and I couldn't able to run test.py successfully.
Regarding to "batch infer now had bug" you mention in README, 
do you mean currently only single image inference works via Pybind11 ?
3. As for int8 mode, I will review soon.

Thanks!!

2021-03-18 06:23 UTC, TCHeish requested changes
int8 mode: 
Please remove some extra files/lines, then int8 mode is good to go!
Thanks.

2021-03-18 06:23 UTC, TCHeish commented on projects/FastRT/fastrt/common/common.hpp
> +#ifndef YOLOV5_COMMON_H_
Not used in fastrt currently, please remove this file. Thanks.

2021-03-18 06:23 UTC, TCHeish commented on projects/FastRT/fastrt/CMakeLists.txt
> +  ${CMAKE_CURRENT_SOURCE_DIR}/common/common.cpp
Not used in fastrt currently, please remove this file. Thanks.

2021-03-18 06:23 UTC, tycallen commented on projects/FastRT/fastrt/meta_arch/baseline.cpp
> +        return addMeanStd(network, weightMap, input, "", mean, std, false); // true for div 255
Cause the mean and std is in 0-255 range, so we don't need div 255 again. In my test only keep it false could make the model output the same like pytorch.

2021-03-18 06:28 UTC, TCHeish commented on projects/FastRT/fastrt/meta_arch/baseline.cpp
> +        return addMeanStd(network, weightMap, input, "", mean, std, false); // true for div 255
I see, thanks!

2021-03-18 06:37 UTC, TCHeish commented on projects/FastRT/fastrt/meta_arch/baseline.cpp
> +        return addMeanStd(network, weightMap, input, "", mean, std, false); // true for div 255
You're right, for the record. No need to div 255.
https://github.com/JDAI-CV/fast-reid/blob/9b5af4166e772f00ddc10f26fbb1f6b6546ad19a/demo/predictor.py#L51
https://github.com/JDAI-CV/fast-reid/blob/9b5af4166e772f00ddc10f26fbb1f6b6546ad19a/fastreid/modeling/meta_arch/baseline.py#L66

2021-03-18 06:47 UTC, tycallen commented on projects/FastRT/test.py
> +from build.pybind_interface.ReID import ReID
Seems everything is OK. Once you get that .so file, it is an importable python lib. Can you import that lib in the same level directory? `from ReID import ReID`. 
The other part I will modify as your suggestion, thank you for your careful review. After that I will find a way to provide a new dockerfile.

2021-03-18 11:57 UTC, TCHeish commented on projects/FastRT/test.py
> +from build.pybind_interface.ReID import ReID
No, I can't import lib in same level directory.

2021-03-18 12:40 UTC, TCHeish commented on projects/FastRT/test.py
> +from build.pybind_interface.ReID import ReID
As for INT8, I just PR a new dockerfile for it.
Last dockefile I didn't install dnn module, you may consider stack on the new one for pybind11.
Thanks.

2021-03-19 08:57 UTC, TCHeish commented on projects/FastRT/test.py
> +from build.pybind_interface.ReID import ReID
I've successfully run test.py, and I will pr a new dockerfile for this(without pytorch install). 
Summery for this dockerfile: 
User can execute both c++ fastrt and test.py via pybind11 in the same container.

So maybe you can just handle the dockerfile of market_benchmark.py (which probably require stack on the env of fastreid with pybind11)
Thanks!

2021-03-23 06:57 UTC, tycallen commented on projects/FastRT/test.py
> +from build.pybind_interface.ReID import ReID
I've finished the modify and provide a dockerfile which could run fastreid, for pybind11, users could use git command in Readme to get it.

2021-03-29 14:54 UTC, TCHeish commented on projects/FastRT/test.py
> +from build.pybind_interface.ReID import ReID
I think it's ok now. Thanks.

2021-04-12 07:05 UTC, merged

2021-04-12 07:05 UTC, L1aoXingyu commented
Good job!